(set-register ?n '(file . "~/.dotfiles/.notes.org"))
(set-register ?x '(file . "~/.xbindkeysrc.scm"))
(set-register ?i '(file . "~/.emacs.d/init.el"))
(set-register ?r '(file . "~/.emacs.d/phil/registers.el"))
(set-register ?k '(file . "~/.ssh/known_hosts"))
(set-register ?m '(file . "~/.xmonad/xmonad.hs"))
(set-register ?p '(file . "~/.lein/profiles.clj"))
